# Generated by Django 4.2.19 on 2025-02-16 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="comment",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="last_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
